/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as MainRouteImport } from './routes/_main'
import { Route as OnboardingSplashRouteImport } from './routes/onboarding/splash'
import { Route as MainSettingsRouteImport } from './routes/_main/settings'
import { Route as MainReceiptsRouteImport } from './routes/_main/receipts'
import { Route as MainHomeRouteImport } from './routes/_main/home'

const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSplashRoute = OnboardingSplashRouteImport.update({
  id: '/onboarding/splash',
  path: '/onboarding/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRoute,
} as any)
const MainReceiptsRoute = MainReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => MainRoute,
} as any)
const MainHomeRoute = MainHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth-callback': typeof AuthCallbackRoute
  '/home': typeof MainHomeRoute
  '/receipts': typeof MainReceiptsRoute
  '/settings': typeof MainSettingsRoute
  '/onboarding/splash': typeof OnboardingSplashRoute
}
export interface FileRoutesByTo {
  '/auth-callback': typeof AuthCallbackRoute
  '/home': typeof MainHomeRoute
  '/receipts': typeof MainReceiptsRoute
  '/settings': typeof MainSettingsRoute
  '/onboarding/splash': typeof OnboardingSplashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/auth-callback': typeof AuthCallbackRoute
  '/_main/home': typeof MainHomeRoute
  '/_main/receipts': typeof MainReceiptsRoute
  '/_main/settings': typeof MainSettingsRoute
  '/onboarding/splash': typeof OnboardingSplashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth-callback'
    | '/home'
    | '/receipts'
    | '/settings'
    | '/onboarding/splash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth-callback'
    | '/home'
    | '/receipts'
    | '/settings'
    | '/onboarding/splash'
  id:
    | '__root__'
    | '/_main'
    | '/auth-callback'
    | '/_main/home'
    | '/_main/receipts'
    | '/_main/settings'
    | '/onboarding/splash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  OnboardingSplashRoute: typeof OnboardingSplashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/splash': {
      id: '/onboarding/splash'
      path: '/onboarding/splash'
      fullPath: '/onboarding/splash'
      preLoaderRoute: typeof OnboardingSplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/receipts': {
      id: '/_main/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof MainReceiptsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/home': {
      id: '/_main/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof MainHomeRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainHomeRoute: typeof MainHomeRoute
  MainReceiptsRoute: typeof MainReceiptsRoute
  MainSettingsRoute: typeof MainSettingsRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainHomeRoute: MainHomeRoute,
  MainReceiptsRoute: MainReceiptsRoute,
  MainSettingsRoute: MainSettingsRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  OnboardingSplashRoute: OnboardingSplashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
